#ifndef _BANEPRO_CONFIG_H
#define _BANEPRO_CONFIG_H

#define BANEPRO_ENABLE_ETHERNET		1
#define BANEPRO_ENABLE_ARP		1
#define BANEPRO_ENABLE_IPV4		1
#define BANEPRO_ENABLE_ICMP		1

#endif /* _BANEPRO_CONFIG_H */
